# global
CONF_SINGLARITY_PATH=singularity
CONF_SCRIPT_PATH=

# minimap2

CONF_MINIMAP2_IMG=
CONF_MINIMAP2_SINGULARITY_OPTION=
CONF_MINIMAP2_REFERENCE=

# nanomonsv-parse

CONF_NANOMONSV_PARSE_IMG=
CONF_NANOMONSV_PARSE_SINGULARITY_OPTION=

# nanomonsv-get

CONF_NANOMONSV_GET_IMG=
CONF_NANOMONSV_GET_SINGULARITY_OPTION=
CONF_NANOMONSV_GET_REFERENCE=
CONF_NANOMONSV_GET_CONTROLPANEL_PREFIX=

# PMDV (PEPPER-Margin-DeepVariant)

CONF_PMDV_IMG=
CONF_PMDV_SINGULARITY_OPTION=
CONF_PMDV_REFERENCE=

#vep-annot

CONF_VEP_ANNOT_IMG=
CONF_VEP_ANNOT_SINGULARITY_OPTION=
CONF_VEP_ANNOT_REFERENCE=
CONF_VEP_ANNOT_DIR_CACHE=
CONF_VEP_ANNOT_PLUGINS=
CONF_VEP_ANNOT_GNOMAD=

#vep-annot-merge

CONF_VEP_ANNOT_MERGE_IMG=
CONF_VEP_ANNOT_MERGE_SINGULARITY_OPTION=

#vep-filt

CONF_VEP_FILT_IMG=
CONF_VEP_FILT_SINGULARITY_OPTION=

#whatshap-phase

CONF_WHATSHAP_PHASE_IMG=
CONF_WHATSHAP_PHASE_SINGULARITY_OPTION=
CONF_WHATSHAP_PHASE_REFERENCE=

#vep-whatshap-phase-merge

CONF_WHATSHAP_PHASE_MERGE_IMG=
CONF_WHATSHAP_PHASE_MERGE_SINGULARITY_OPTION=

#whatshap-haplotag

CONF_WHATSHAP_HAPLOTAG_IMG=
CONF_WHATSHAP_HAPLOTAG_SINGULARITY_OPTION=
CONF_WHATSHAP_HAPLOTAG_REFERENCE=


# GenomonFisher

CONF_GenomonFisher_IMG=
CONF_GenomonFisher_SINGULARITY_OPTION=
CONF_GenomonFisher_REFERENCE=


# aggreaget_mpileup

CONF_aggregate_mpileup_IMG=
CONF_aggreaget_mpileup_SINGULARITY_OPTION=
CONF_aggreaget_mpileup_BLACK_LIST=
CONF_aggreaget_mpileup_BLACK_LIST_HEADER=
CONF_aggreaget_mpileup_REFERENCE=
CONF_aggreaget_mpileup_ANNOTATION_HEADER=
CONF_aggreaget_mpileup_GNOMAD=

# etltools

CONF_etltools_IMG=
CONF_etltools_SINGULARITY_OPTION=
CONF_etltools_REFERENCE=
